### ISSUE TITLE
503 Error while trying to list contents

### ISSUE THREAD

**Issue by leonardobiagioli** [lumapps/lumapps-sdk#47] opened 2019-07-29 15:22 UTC
Hi, I am trying to collect contents through the following code
```
from lumapps.client import ApiClient
api = ApiClient(credentials=get_credential(customer_id))
contents = api.get_call("content", "list", body={"lang":"en", "instance": [str(instance_id)]})
```
the get_credential() function returns a Credential object stored in Cloud Datastore.

I am receiving a 503 error back as below
`HttpError: <HttpError 503 when requesting https://lumsites.appspot.com/_ah/api/lumsites/v1/content/list?alt=json returned "int() argument must be a string or a number, not 'NoneType'">`

What does it mean? What am I doing wrong?
Thanks,
Leonardo

**Comment by maximevast** [comment] 2019-07-29 15:29
Hi Leonardo, 

Thanks for using LumApps SDK

According to the [API documentation](https://api.lumapps.com/docs/output/_schemas/servercontentcontentmessagescontentlistrequest), you should be using `instanceId` rather than `instance`

Can you try with this parameter?

Please keep me posted.

Regards

Maxime

**Comment by leonardobiagioli** [comment] 2019-07-29 15:48
Same error
HttpError: <HttpError 503 when requesting
https://lumsites.appspot.com/_ah/api/lumsites/v1/content/list?alt=json
returned "int() argument must be a string or a number, not 'NoneType'">

**Comment by maximevast** [comment] 2019-07-30 07:23
Good morning Leonardo,

I can't seem to reproduce your issue.
Can you please check the value of `str(instance_id)`?

Best

Maxime

**Comment by leonardobiagioli** [comment] 2019-07-30 14:04
Yes, that is properly set, I have tried both `str(instance_id)` and `[str(instance_id)]`, the error still occurs.
It seems the request is trying to pass a required parameters and this is not provided... Do you have a list of required parameters?

**Comment by maximevast** [comment] 2019-07-30 14:49
Ok, I checked the logs and your issue might be an API issue. I'm asking the team to investigate. In the meantime, could you:

- check that your credentials are correct
- add the `customerId` parameter as a string to your request body.

Best

**Comment by leonardobiagioli** [comment] 2019-07-30 15:45
Thank you for the help!
Now the error has changed
`HttpError: <HttpError 503 when requesting https://lumsites.appspot.com/_ah/api/lumsites/v1/content/list?alt=json returned "'NoneType' object has no attribute 'hasFeature'">`

**Comment by maximevast** [comment] 2019-07-30 15:55
Great, this confirms the origin of your problem:
It seems that your service account has no user associated with.

Please make sure to follow the [Service Account with delegation](https://github.com/lumapps/lumapps-sdk/wiki/Authentication-With-Service-Discovery#service-account-with-delegation) chapter on the sdk wiki. (The customerId should not be required once the delegation problem fixed)

Please let me know

Maxime

**Comment by leonardobiagioli** [comment] 2019-07-31 05:07
Hi Maxime,
I have followed the guide here https://api.lumapps.com/docs/start , in particular the "Strategy 2: user approval authentication", does it require the delegation as well?
Thanks

**Comment by maximevast** [comment] 2019-07-31 08:20
What I can see from our logs is that the calls you made to the API are "anonymous".

Your token needs to be linked to a user. the delegation is for the service account method.
If you used oauth2, please refer to the Google [documentation](https://developers.google.com/identity/protocols/OAuth2WebServer).

**Comment by ulodciv** [comment] 2019-12-03 10:24
Thank you for taking the time to report this issue and helping to make LumApp SDK better. There have been many changes in LumApp SDK since that time you reported the issue and your it may have been fixed with some of the updates. Do not hesitate to open a new issue if you still need assistance.

**Closed by ulodciv** 2019-12-03 10:24 UTC
